---

    extends: nutshell

    parserOptions:
        sourceType: script

    env:
        node: true

    rules:
        import/no-commonjs: 0
        key-spacing:
            - 2
            - align: colon
        quote-props:
            - 2
            - always
        strict:
            - 2
            - global
